version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - database:/var/lib/postgresql/data
    networks:
      - net
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    networks:
      - net
  rdv:
    build: 
      context: "./"
      dockerfile: "./docker/web/Dockerfile"
    links:
      - database
    ports:
      - '3000:3000'
    environment:
      HOST: http://localhost:3000
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lapin_development
      DATABASE_URL: postgres://postgres:postgres@database:5432/lapin_development
      RAILS_ENV: development
      RACK_ENV: development 
      RAILS_SERVE_STATIC_FILES: enabled
      RAILS_LOG_TO_STDOUT: enabled
      REDIS_URL: redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@cache:6379
    networks:
      - net
  job:
    build: 
      context: "./"
      dockerfile: "./docker/job/Dockerfile"
    links:
      - rdv
      - database
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/lapin_development
      RAILS_ENV: development
      RACK_ENV: development
      RAILS_SERVE_STATIC_FILES: enabled
      RAILS_LOG_TO_STDOUT: enabled
      REDIS_URL: redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@cache:6379
    networks:
      - net
  script:
    build: 
      context: "./"
      dockerfile: "./docker/script/Dockerfile"
    command: "bin/rails db:migrate RAILS_ENV=$RAILS_ENV"
    links:
      - rdv
      - database
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/lapin_development
      RAILS_ENV: development
      RACK_ENV: development
      RAILS_SERVE_STATIC_FILES: enabled
      RAILS_LOG_TO_STDOUT: enabled
      REDIS_URL: redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@cache:6379
    networks:
      - net
volumes:
  database:
    driver: local
  cache:
    driver: local
networks:
  net:
