name: Push docker image from branch
on: 
  push: 
    branches:
      - recette
# Env variable
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  DOCKER_REPO_NAME: ${{secrets.DOCKER_REPO_NAME}}
  WEBAPP_DOCKERFILE: ./docker/web/Dockerfile
  JOB_DOCKERFILE: ./docker/job/Dockerfile
  SCRIPT_DOCKERFILE: ./docker/script/Dockerfile
  git_hash: $(git rev-parse --short $GITHUB_SHA)
jobs:
  push-image:  # job name
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version)
    environment: lapin-beta-gouv
    steps:
    - uses: actions/checkout@v2 # first action : checkout source code

    - name: Check Hash
      run: echo ${GITHUB_SHA::8}

    - name: docker login
      run: | # log into docker registry account
        docker login $DOCKER_REPO_NAME -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Get current date # get the date of the build
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"

    - name: Build the Webapp Docker image
      run: docker build . --file $WEBAPP_DOCKERFILE --tag $DOCKER_REPO_NAME/webapp:$GITHUB_REF_NAME-${GITHUB_SHA::8}-${{ steps.date.outputs.date }}
    - name: Docker Push Webapp image
      run: docker push $DOCKER_REPO_NAME/webapp:$GITHUB_REF_NAME-${GITHUB_SHA::8}-${{ steps.date.outputs.date }}
    - name: Build the Job Docker image
      run: docker build . --file $JOB_DOCKERFILE --tag $DOCKER_REPO_NAME/jobs:$GITHUB_REF_NAME-${GITHUB_SHA::8}-${{ steps.date.outputs.date }}
    - name: Docker Push Job image
      run: docker push $DOCKER_REPO_NAME/jobs:$GITHUB_REF_NAME-${GITHUB_SHA::8}-${{ steps.date.outputs.date }}
    - name: Build the Script Docker image
      run: docker build . --file $SCRIPT_DOCKERFILE --tag $DOCKER_REPO_NAME/script:$GITHUB_REF_NAME-${GITHUB_SHA::8}-${{ steps.date.outputs.date }}
    - name: Docker Push Script image
      run: docker push $DOCKER_REPO_NAME/script:$GITHUB_REF_NAME-${GITHUB_SHA::8}-${{ steps.date.outputs.date }}